name: Linter

on: [pull_request, push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - name: Install dependency
        run: pnpm install
      - name: Build
        run: pnpm lint:fix
